config/routes.rb
ThinkFeelDoDashboard::Engine.routes.draw do
  root to: "admin#index"
  resources :arms
  resources :groups do
    namespace :social_networking do
      resources :profile_questions
    end
    resource :moderators, only: :create
  end
  resources :participants do
    resources :coaches, controller: :coach_assignments, except: [:index] do
      get 'woz', on: :member
    end
    resources :groups, controller: :memberships, except: [:index]
  end
  resources :reports
  resources :users
end

app/models/membership.rb
# Memberships are the relationship between groups and participants
# The important note here is that there is only ONE ACTIVE
# Membership for each participant at a time
class Membership < ActiveRecord::Base
  belongs_to :group
  belongs_to :active_group,
             class_name: "Group",
             foreign_key: :group_id,
             inverse_of: :active_memberships
  belongs_to :participant
  belongs_to :active_participant,
             class_name: "Participant",
             foreign_key: :participant_id,
             inverse_of: :active_membership

  validates :group, :participant, presence: true

  delegate :name, to: :group, prefix: true
  delegate :name, to: :participant, prefix: true

  scope :active, lambda {
    where("start_date <= ? OR start_date = ?", Date.today, nil)
    .where("end_date >= ? OR end_date = ?", Date.today, nil)
  }
end

app/models/think_feel_do_dashboard/coach_assignment.rb
module ThinkFeelDoDashboard
  class CoachAssignment < ActiveRecord::Base
    belongs_to :coach, class_name: "User"
    belongs_to :participant

    validates :coach, :participant, presence: true

    delegate :name, to: :coach, prefix: true
    delegate :name, to: :participant, prefix: true
  end
end

app/models/think_feel_do_dashboard/concerns/group.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # Creates moderator and adds validations
    # and associations to group
    module Group
      extend ActiveSupport::Concern

      included do
        has_many :profile_questions,
                 class_name: "SocialNetworking::ProfileQuestion"
        belongs_to :moderator,
                   class_name: "User",
                   foreign_key: :moderator_id

        before_validation :create_moderator,
                          if: proc { |g| g.arm && g.arm.social? }

        validates :moderator_id,
                  presence: true,
                  if: proc { |g| g.arm && g.arm.social? }
      end

      def moderating_participant
        return if active_memberships.empty?
        active_participants.find_by_is_admin(true)
      end

      private

      def create_moderator
        unless moderating_participant
          begin
            create_moderating_participant
          rescue ActiveRecord::RecordInvalid => e
            errors.add(:base, "There were errors: #{e}")
          end
        end
      end

      def create_moderating_participant
        days = ENV["MODERATOR_LIFESPAN"] || 365

        ActiveRecord::Base.transaction do
          participant = create_participant(SecureRandom.hex(8))
          create_profile(participant.id)
          memberships.build(
            participant_id: participant.id,
            start_date: Time.zone.today,
            end_date: Time.zone.today.advance(days: days)
          )
        end
      end

      def create_participant(study_id)
        password = "1Aa" + SecureRandom.base64.gsub(/(.{1})/, '\1 ')

        ::Participant.create!(
          contact_preference: "email",
          display_name: Rails.application
                             .config
                             .moderating_participant_display_name,
          email: "#{study_id}@example.com",
          is_admin: true,
          password: password,
          password_confirmation: password,
          study_id: study_id
        )
      end

      def create_profile(participant_id)
        ::SocialNetworking::Profile.create!(
          participant_id: participant_id,
          icon_name: "admin",
          active: true
        )
      end
    end
  end
end

app/models/think_feel_do_dashboard/concerns/membership.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # addes necessary membership
    # associations and validations
    module Membership
      extend ActiveSupport::Concern

      # This is perfect for including functionality
      # provided by 3rd party gems, etc.
      included do
        attr_accessor :display_name

        before_validation :ensure_display_name_for_social_arms
        before_validation :only_one_active_group, on: :create

        validate :excludes_moderators
      end

      # methods added to Class itself...
      module ClassMethods
      end

      def active?
        (start_date.nil? || start_date <= Time.zone.today) &&
          (end_date.nil? || end_date >= Time.zone.today)
      end

      private

      def ensure_display_name_for_social_arms
        if invalid_display_name?
          errors.add(:display_name,
                     "is required because the arm of this intervention " \
                     "utilizes social features.")
        else
          name = display_name || participant.display_name
          participant.update_attributes(display_name: name)
        end
      end

      def excludes_moderators
        if active_group.try(:arm) &&
           !active_group.arm.social? &&
           participant.is_admin
          errors.add(:base, "moderators can't be part of this group.")
        end
      end

      def only_one_active_group
        if participant.active_membership && active?
          errors.add(:participant,
                     "can't be assigned to this group because they are " \
                     "already active.")
        end
      end

      def invalid_display_name?
        participant.active_membership &&
          active_group.try(:arm).try(:social?) &&
          participant.display_name.blank?
      end
    end
  end
end

app/models/think_feel_do_dashboard/concerns/password.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # is included in the User model and automatically
    # sets a password on create
    module Password
      extend ActiveSupport::Concern

      # This is perfect for including functionality
      # provided by 3rd party gems, etc.
      included do
        before_validation :set_password, on: :create
      end

      # methods added to Class itself...
      module ClassMethods
      end

      private

      def set_password
        random_string = SecureRandom.hex(64)
        self.password = random_string
        self.password_confirmation = random_string
      end
    end
  end
end

app/models/think_feel_do_dashboard/enrollment.rb
module ThinkFeelDoDashboard
  class Enrollment < ActiveRecord::Base
    belongs_to :coach, class_name: "User"
    belongs_to :group
    belongs_to :participant
  end
end

app/controllers/think_feel_do_dashboard/admin_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Allows the admin to navigate from page to page
  class AdminController < ApplicationController
    # GET /think_feel_do_dashboard
    def index
      authorize! :index, Arm
    end
  end
end

app/controllers/think_feel_do_dashboard/application_controller.rb
# frozen_string_literal: true
require "cancancan"

module ThinkFeelDoDashboard
  # Top level engine controller
  # inherits from host application's ApplicationController.
  class ApplicationController < ::ApplicationController
    include Concerns::BrowserDetective
    include Concerns::InvalidAuthToken

    before_action :authenticate_user!, :detect_browser
    check_authorization

    layout "application"

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_url, alert: exception.message
    end
  end
end

app/controllers/think_feel_do_dashboard/arms_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Allows for the creation, updating, and deletion of arms
  class ArmsController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :arm_not_found

    # GET /think_feel_do_dashboard/arms
    def index
      authorize! :index, Arm
      @arms = Arm.includes(:groups)
    end

    # POST /think_feel_do_dashboard/arms
    def create
      authorize! :create, Arm
      @arm = Arm.new(arm_params)
      if @arm.save
        redirect_to @arm,
                    notice: "Arm was successfully created."
      else
        render :new
      end
    end

    # GET /think_feel_do_dashboard/arms/new
    def new
      authorize! :new, Arm
      @arm = Arm.new
    end

    # GET /think_feel_do_dashboard/arms/1
    def show
      @arm = Arm.find(params[:id])
      authorize! :show, @arm
      @lesson = @arm.bit_core_tools.find_by_type("Tools::Learn")
    end

    # GET /think_feel_do_dashboard/arms/1/edit
    def edit
      @arm = Arm.find(params[:id])
      authorize! :edit, @arm
    end

    # PATCH/PUT /think_feel_do_dashboard/arms/1
    def update
      @arm = Arm.find(params[:id])
      authorize! :update, @arm
      if @arm.update(arm_params)
        redirect_to arm_path(@arm),
                    notice: "Arm was successfully updated.",
                    only: true
      else
        render :edit
      end
    end

    # DELETE /think_feel_do_dashboard/arms/1
    def destroy
      @arm = Arm.find(params[:id])
      authorize! :destroy, @arm
      redirect_to arm_path(@arm),
                  notice: "You do not have privileges to delete an arm. "\
                  "Please contact the site administrator to remove this arm."
    end

    private

    def arm_params
      params
        .require(:arm)
        .permit(
          :title, :is_social, :has_woz, :can_message_after_membership_complete
        )
    end

    def arm_not_found
      redirect_to arms_path,
                  alert: "The arm you were looking for no longer exists."
    end
  end
end

app/controllers/think_feel_do_dashboard/coach_assignments_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Used to associated coaches with participants
  class CoachAssignmentsController < ApplicationController
    before_action :set_participant
    before_action :set_coaches
    before_action :set_coach_assignment,
                  only: [:new, :show, :edit, :update, :destroy]

    # GET /think_feel_do_dashboard/participants/1/coaches/new
    def new
      authorize! :new, CoachAssignment
    end

    # POST /think_feel_do_dashboard/participants/1/coaches
    def create
      authorize! :create, CoachAssignment
      @coach_assignment = @participant.build_coach_assignment(
        coach_assignment_params
      )

      if @coach_assignment.save
        redirect_to participant_path(@participant),
                    notice: "Coach/Moderator was successfully assigned."
      else
        render :new
      end
    end

    # GET /think_feel_do_dashboard/participants/1/coaches/1
    def show
      authorize! :read, @coach_assignment
    end

    # GET /think_feel_do_dashboard/participants/1/coaches/1/edit
    def edit
      authorize! :edit, @coach_assignment
    end

    # PATCH/PUT /think_feel_do_dashboard/participants/1/coaches/1
    def update
      authorize! :update, @coach_assignment
      if @coach_assignment.update(coach_assignment_params)
        redirect_to participant_path(
          @participant
        ),
                    notice: "Coach/Moderator was successfully assigned."
      else
        render :edit
      end
    end

    # DELETE /think_feel_do_dashboard/participants/1/coaches/1
    def destroy
      authorize! :destroy, @coach_assignment
      if @coach_assignment.destroy
        redirect_to participant_path(@participant),
                    notice: "Coach/Moderator was successfully removed."
      else
        redirect_to participant_path(@participant),
                    alert: "There were errors."
      end
    end

    # GET /think_feel_do_dashboard/participants/1/coaches/woz
    def woz
      if @participant.coach
        set_coach_assignment
        authorize! :edit, @coach_assignment

        update_woz_coach
      else
        authorize! :new, CoachAssignment
        set_new_woz_coach
      end
    end

    private

    def set_new_woz_coach
      @coach_assignment = CoachAssignment.new(
        participant: @participant,
        coach_id: @participant.active_group.moderator_id
      )
      if @coach_assignment.save
        notification = "Coach/Moderator was successfully assigned"
      else
        notification = "An error occurred in the update of the "\
                              "participant's coach to the WOZ moderator."
      end
      redirect_to participant_path(@participant), notice: notification
    end

    def update_woz_coach
      @coach_assignment.update(coach_id: @participant.active_group.moderator_id)
      if @coach_assignment.save
        notification = "Coach/Moderator was successfully assigned "
      else
        notification = "An error occurred in the update of the "\
                              "participant's coach to the moderator."
      end
      redirect_to participant_path(@participant), notice: notification
    end

    def set_coaches
      @coaches = User.all.map { |user| [user.email, user.id] }
    end

    def set_participant
      @participant = Participant.find(params[:participant_id])
    end

    def set_coach_assignment
      @coach_assignment = @participant.coach_assignment ||
                          @participant.build_coach_assignment
    end

    def coach_assignment_params
      params
        .require(:coach_assignment)
        .permit(:coach_id)
    end
  end
end

app/controllers/think_feel_do_dashboard/concerns/browser_detective.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # Methods for browser type detection.
    module BrowserDetective
      extend ActiveSupport::Concern

      private

      # See http://richonrails.com/articles/action-pack-variants-in-rails-4-1
      def detect_browser
        request.variant = case request.user_agent
                          when /iPad/i
                            :tablet
                          when /iPhone|Windows Phone/i
                            :phone
                          when /Android/i && /mobile/i
                            :phone
                          when /Android/i
                            :tablet
                          else
                            :desktop
                          end
      end
    end
  end
end

app/controllers/think_feel_do_dashboard/concerns/invalid_auth_token.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # Rescues exception when authenticity token has expired
    module InvalidAuthToken
      extend ActiveSupport::Concern

      included do
        rescue_from ActionController::InvalidAuthenticityToken,
                    with: :invalid_auth_token_redirect
      end

      private

      def invalid_auth_token_redirect
        redirect_to root_path,
                    alert: "Your authenticity token expired. Please try again."
      end
    end
  end
end

app/controllers/think_feel_do_dashboard/groups_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Allows for the creation, updating, and deletion of groups
  class GroupsController < ApplicationController
    before_action :set_arms, :set_users
    before_action :set_group, :set_arm,
                  only: [:show, :edit, :update, :destroy]
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    # GET /think_feel_do_dashboard/groups
    def index
      authorize! :index, Group
      @groups = Group.all
    end

    # POST /think_feel_do_dashboard/groups
    def create
      @group = Group.new(group_params.except(:user_id))
      authorize! :create, @group

      if @group.save
        redirect_to @group,
                    notice: "Group was successfully created."
      else
        render :new
      end
    end

    # GET /think_feel_do_dashboard/groups/new
    def new
      authorize! :new, Group
      @group = Group.new
    end

    # GET /think_feel_do_dashboard/groups/1
    def show
      authorize! :show, @group
    end

    # GET /think_feel_do_dashboard/groups/1/edit
    def edit
      authorize! :edit, @group
    end

    # PATCH/PUT /think_feel_do_dashboard/groups/1
    def update
      authorize! :update, @group
      if @group.update(group_params.except(:user_id))
        redirect_to group_path(@group),
                    notice: "Group was successfully updated.",
                    only: true
      else
        render :edit
      end
    end

    # DELETE /think_feel_do_dashboard/groups/1
    def destroy
      authorize! :destroy, @group
      @group.destroy
      response_status = { notice: "Group was successfully destroyed." }
    rescue ActiveRecord::DeleteRestrictionError => e
      response_status = { alert: e.message }
    ensure
      redirect_to groups_url, response_status
    end

    private

    def set_group
      @group = Group.find(params[:id])
    end

    def set_arm
      @arm = @group.arm
    end

    def set_arms
      @arms = Arm.all
    end

    def set_users
      @users = User.all
    end

    def group_params
      params.require(:group).permit(
        :arm_id, :title, :moderator_id
      )
    end

    def record_not_found
      redirect_to main_app.root_path,
                  alert: "The group you are looking for no longer exists."
    end
  end
end

app/views/think_feel_do_dashboard/memberships/_dates.html.erb
<% membership = membership || Membership.new %>
<div class="form-group">
  <%= label_tag "membership[start_date]", "Start Date" %>
  <%= text_field_tag "membership[start_date]", {}, type: :date, class: "form-control", value: (membership.start_date || Time.zone.today) %>
</div>
<div class="form-group">
  <%= label_tag "membership[end_date]", "End Date" %>
  <%= text_field_tag "membership[end_date]", {}, type: :date, class: "form-control", value: (membership.end_date || Time.zone.today + 1.week) %>
</div>
<% if Rails.application.config.study_length_in_weeks %>
  <p>
    Standard number of weeks: <%= Rails.application.config.study_length_in_weeks %>,
    Projected End Date from today: <label id="membership_end_date_calculation"><%= projected_end_date(membership) %></label>
  </p>
<% end %>

<% if Rails.application.config.study_length_in_weeks %>

<% end %>

app/views/think_feel_do_dashboard/memberships/_form.html.erb
<%= form_for(@membership, url: url, html: { role: :form }) do |f| %>
  <% if @membership.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <strong><%= pluralize(@membership.errors.count, "error") %> prohibited this group from being assigned to this participant:</strong>
      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @participant.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <strong><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being updated:</strong>
      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Participant:</strong>
    <%= @participant.study_id %>
  </p>

  <div class="form-group">
    <%= f.label :group_id %>
    <% if @membership.new_record? %>
      <%= f.select :group_id, grouped_options_for_select(@group_options, @membership.group_id), { prompt: "Select Group" }, { class: "form-control" } %>
    <% else %>
      <span class="form-control-static"><%= @membership.group.title %></span>
    <% end %>
  </div>

  <% if social_features? && (@membership.new_record? || @membership.group.arm.social?) %>
    <div class="form-group">
      <%= f.label :display_name, "Display Name" %>
      <%= f.text_field :display_name, class: "form-control", value: @participant.display_name %>
      <p class="help-block">Only necessary for enrollments where socializing is a feature of the arm.</p>
    </div>
  <% end %>

  <%= render "dates", membership: @membership %>

  <%= f.submit button_text, class: "btn btn-primary" %>
  <%= link_to "Cancel", cancel_path, class: "btn btn-default" %>
<% end %>

app/views/think_feel_do_dashboard/memberships/edit.html.erb
<h1>Editing Group Assigned to Participant</h1>

<%= render 'form', button_text: "Update", cancel_path: participant_path(@participant), url: participant_group_path(@participant, @membership.group) %>

app/views/think_feel_do_dashboard/memberships/new.html.erb
<h1>Assigning New Group to Participant</h1>

<%= render 'form', button_text: "Assign", cancel_path: participant_path(@participant), url: participant_groups_path(@participant) %>

app/views/think_feel_do_dashboard/memberships/show.html.erb
<h1>Membership</h1>

<div class="btn-toolbar" role="toolbar">
  <%= link_to "Participant", participant_path(@membership.participant), class: "btn btn-default" %>
  <%= link_to "Edit", edit_participant_group_path(@membership.participant, @membership.group), class: "btn btn-default" %>
  <%= link_to "Destroy", participant_group_path(@membership.participant, @membership.group), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
</div>
<p>
  <strong>Participant:</strong>
  <%= link_to @membership.participant.study_id, participant_path(@membership.participant) %>
</p>
<p>
  <strong>Group:</strong>
  <%= link_to @membership.group.title, group_path(@membership.group) %>
</p>

<% if social_features? && @membership.group.arm.social? %>
  <p>
    <strong>Display Name:</strong>
    <%= @membership.participant.display_name %>
  </p>
<% end %>

<p>
  <strong>Membership Status:</strong>
  <%= membership_status @membership.participant, @membership %>
</p>
<p>
  <strong>Start Date:</strong>
  <%= l(@membership.start_date, format: :standard) %>
</p>
<p>
  <strong>End Date:</strong>
  <%= l(@membership.end_date, format: :standard) %>
</p>