config/routes.rb
ThinkFeelDoDashboard::Engine.routes.draw do
  root to: "admin#index"
  resources :arms
  resources :groups do
    namespace :social_networking do
      resources :profile_questions
    end
    resource :moderators, only: :create
  end
  resources :participants do
    resources :coaches, controller: :coach_assignments, except: [:index] do
      get 'woz', on: :member
    end
    resources :groups, controller: :memberships, except: [:index]
  end
  resources :reports
  resources :users
end

app/controllers/think_feel_do_dashboard/social_networking/profile_questions_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  module SocialNetworking
    # Allows for the creation, updating, and deletion of social networking
    # profile questions
    class ProfileQuestionsController < ApplicationController
      before_action :set_profile_question, except: [:index, :new, :create]
      before_action :set_group, :authorize_group_access!

      def index
        @profile_questions = ::SocialNetworking::ProfileQuestion
                             .where(group_id: params[:group_id])
      end

      def create
        @profile_question = @group.profile_questions
                                  .build(profile_question_params)
        if @profile_question.save
          redirect_to group_social_networking_profile_questions_path(@group),
                      notice: "Profile Question was successfully created."
        else
          render :new
        end
      end

      def new
        @profile_question = ::SocialNetworking::ProfileQuestion.new
      end

      def edit
      end

      def update
        if @profile_question.update(profile_question_params)
          redirect_to group_social_networking_profile_questions_path(@group),
                      notice: "Profile Question was successfully updated."
        else
          render :edit
        end
      end

      def destroy
        if @profile_question.destroy
          redirect_to group_social_networking_profile_questions_path(@group),
                      notice: "Profile Question was successfully removed."
        else
          redirect_to group_social_networking_profile_questions_path(@group),
                      alert: "There were errors."
        end
      end

      private

      def authorize_group_access!
        authorize! :moderate, @group
      end

      def set_group
        @group = Group.find(params[:group_id])

      rescue ActiveRecord::RecordNotFound => e
        redirect_to root_path, alert: e.message
      end

      def set_profile_question
        @profile_question = ::SocialNetworking::ProfileQuestion
                            .find(params[:id])

      rescue ActiveRecord::RecordNotFound => e
        redirect_to root_path, alert: e.message
      end

      def profile_question_params
        params.require(:social_networking_profile_question).permit(
          :group_id, :question_text
        )
      end
    end
  end
end

app/views/think_feel_do_dashboard/social_networking/profile_questions/_form.html.erb
<% if @profile_question.errors.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <strong><%= pluralize(@profile_question.errors.count, "error") %> prohibited this group from being saved:</strong>
    <ul>
    <% @profile_question.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="form-group">
  <%= f.label :question_text %>
  <%= text_field_tag "social_networking_profile_question[question_text]", @profile_question.question_text, class: "form-control" %>
</div>

<%= f.submit button_text, class: "btn btn-primary" %>
<%= link_to "Cancel", group_path(@group), class: "btn btn-default" %>

app/views/think_feel_do_dashboard/social_networking/profile_questions/edit.html.erb
<h1>Edit Profile Question</h1>

<%= form_for([@group, @profile_question], url: group_social_networking_profile_question_path(@group, @profile_question), html: { role: :form }) do |f| %>
  <%= render 'form', button_text: "Update", cancel_path: group_social_networking_profile_questions_path(@group), f: f %>
<% end %>

app/views/think_feel_do_dashboard/social_networking/profile_questions/index.html.erb
<h1>Profile Questions</h1>

<div class="btn-toolbar" role="toolbar">
  <%= link_to "Back", group_path(@group), class: "btn btn-default" %>
  <%= link_to "New", new_group_social_networking_profile_question_url(@group), class: "btn btn-default" %>
</div>

<table class="table">
  <tr>
    <th>Question Text</th>
    <th colspan="2"></th>
  </tr>
  <% @profile_questions.each do |profile_question| %>
    <tr>
      <td><%= profile_question.question_text %></td>
      <td><%= link_to "edit", edit_group_social_networking_profile_question_path(@group, profile_question) %></td>
      <td><%= link_to 'delete', group_social_networking_profile_question_path(@group, profile_question), method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/think_feel_do_dashboard/social_networking/profile_questions/new.html.erb
<h1>New Profile Question</h1>

<%= form_for([@group, @profile_question], url: group_social_networking_profile_questions_path(@group), html: { role: :form }) do |f| %>
  <%= render 'form', button_text: "Create", cancel_path: group_social_networking_profile_questions_path(@group), f: f %>
<% end %>