config/routes.rb
ThinkFeelDoDashboard::Engine.routes.draw do
  root to: "admin#index"
  resources :arms
  resources :groups do
    namespace :social_networking do
      resources :profile_questions
    end
    resource :moderators, only: :create
  end
  resources :participants do
    resources :coaches, controller: :coach_assignments, except: [:index] do
      get 'woz', on: :member
    end
    resources :groups, controller: :memberships, except: [:index]
  end
  resources :reports
  resources :users
end

app/models/participant.rb
# A Participant is anyone who is participanting in a study
# Please keep in mind that a participant is tied to a group, thus
# Every participant is inherently part of at least one group
class Participant < ActiveRecord::Base
  has_one :coach_assignment, dependent: :destroy
  has_one :coach, class_name: "User", through: :coach_assignment
  has_many :memberships, dependent: :destroy
  has_one :active_membership,
    -> { active },
    class_name: "Membership",
    foreign_key: :participant_id,
    dependent: :destroy,
    inverse_of: :active_participant
  has_many :groups, through: :memberships
  has_one :active_group, through: :active_membership

  validates :phone_number, allow_nil: true, allow_blank: true, uniqueness: true
  validates :study_id, :email, presence: true, uniqueness: true
  validates :contact_preference, presence: true, inclusion: %w(email phone)

  delegate :name, to: :coach, allow_nil: true, prefix: true

  def name
    email
  end
end

app/models/think_feel_do_dashboard/coach_assignment.rb
module ThinkFeelDoDashboard
  class CoachAssignment < ActiveRecord::Base
    belongs_to :coach, class_name: "User"
    belongs_to :participant

    validates :coach, :participant, presence: true

    delegate :name, to: :coach, prefix: true
    delegate :name, to: :participant, prefix: true
  end
end

app/models/think_feel_do_dashboard/concerns/group.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # Creates moderator and adds validations
    # and associations to group
    module Group
      extend ActiveSupport::Concern

      included do
        has_many :profile_questions,
                 class_name: "SocialNetworking::ProfileQuestion"
        belongs_to :moderator,
                   class_name: "User",
                   foreign_key: :moderator_id

        before_validation :create_moderator,
                          if: proc { |g| g.arm && g.arm.social? }

        validates :moderator_id,
                  presence: true,
                  if: proc { |g| g.arm && g.arm.social? }
      end

      def moderating_participant
        return if active_memberships.empty?
        active_participants.find_by_is_admin(true)
      end

      private

      def create_moderator
        unless moderating_participant
          begin
            create_moderating_participant
          rescue ActiveRecord::RecordInvalid => e
            errors.add(:base, "There were errors: #{e}")
          end
        end
      end

      def create_moderating_participant
        days = ENV["MODERATOR_LIFESPAN"] || 365

        ActiveRecord::Base.transaction do
          participant = create_participant(SecureRandom.hex(8))
          create_profile(participant.id)
          memberships.build(
            participant_id: participant.id,
            start_date: Time.zone.today,
            end_date: Time.zone.today.advance(days: days)
          )
        end
      end

      def create_participant(study_id)
        password = "1Aa" + SecureRandom.base64.gsub(/(.{1})/, '\1 ')

        ::Participant.create!(
          contact_preference: "email",
          display_name: Rails.application
                             .config
                             .moderating_participant_display_name,
          email: "#{study_id}@example.com",
          is_admin: true,
          password: password,
          password_confirmation: password,
          study_id: study_id
        )
      end

      def create_profile(participant_id)
        ::SocialNetworking::Profile.create!(
          participant_id: participant_id,
          icon_name: "admin",
          active: true
        )
      end
    end
  end
end

app/models/think_feel_do_dashboard/concerns/membership.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # addes necessary membership
    # associations and validations
    module Membership
      extend ActiveSupport::Concern

      # This is perfect for including functionality
      # provided by 3rd party gems, etc.
      included do
        attr_accessor :display_name

        before_validation :ensure_display_name_for_social_arms
        before_validation :only_one_active_group, on: :create

        validate :excludes_moderators
      end

      # methods added to Class itself...
      module ClassMethods
      end

      def active?
        (start_date.nil? || start_date <= Time.zone.today) &&
          (end_date.nil? || end_date >= Time.zone.today)
      end

      private

      def ensure_display_name_for_social_arms
        if invalid_display_name?
          errors.add(:display_name,
                     "is required because the arm of this intervention " \
                     "utilizes social features.")
        else
          name = display_name || participant.display_name
          participant.update_attributes(display_name: name)
        end
      end

      def excludes_moderators
        if active_group.try(:arm) &&
           !active_group.arm.social? &&
           participant.is_admin
          errors.add(:base, "moderators can't be part of this group.")
        end
      end

      def only_one_active_group
        if participant.active_membership && active?
          errors.add(:participant,
                     "can't be assigned to this group because they are " \
                     "already active.")
        end
      end

      def invalid_display_name?
        participant.active_membership &&
          active_group.try(:arm).try(:social?) &&
          participant.display_name.blank?
      end
    end
  end
end

app/models/think_feel_do_dashboard/concerns/password.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # is included in the User model and automatically
    # sets a password on create
    module Password
      extend ActiveSupport::Concern

      # This is perfect for including functionality
      # provided by 3rd party gems, etc.
      included do
        before_validation :set_password, on: :create
      end

      # methods added to Class itself...
      module ClassMethods
      end

      private

      def set_password
        random_string = SecureRandom.hex(64)
        self.password = random_string
        self.password_confirmation = random_string
      end
    end
  end
end

app/controllers/think_feel_do_dashboard/admin_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Allows the admin to navigate from page to page
  class AdminController < ApplicationController
    # GET /think_feel_do_dashboard
    def index
      authorize! :index, Arm
    end
  end
end

app/controllers/think_feel_do_dashboard/application_controller.rb
# frozen_string_literal: true
require "cancancan"

module ThinkFeelDoDashboard
  # Top level engine controller
  # inherits from host application's ApplicationController.
  class ApplicationController < ::ApplicationController
    include Concerns::BrowserDetective
    include Concerns::InvalidAuthToken

    before_action :authenticate_user!, :detect_browser
    check_authorization

    layout "application"

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_url, alert: exception.message
    end
  end
end

app/controllers/think_feel_do_dashboard/arms_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Allows for the creation, updating, and deletion of arms
  class ArmsController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :arm_not_found

    # GET /think_feel_do_dashboard/arms
    def index
      authorize! :index, Arm
      @arms = Arm.includes(:groups)
    end

    # POST /think_feel_do_dashboard/arms
    def create
      authorize! :create, Arm
      @arm = Arm.new(arm_params)
      if @arm.save
        redirect_to @arm,
                    notice: "Arm was successfully created."
      else
        render :new
      end
    end

    # GET /think_feel_do_dashboard/arms/new
    def new
      authorize! :new, Arm
      @arm = Arm.new
    end

    # GET /think_feel_do_dashboard/arms/1
    def show
      @arm = Arm.find(params[:id])
      authorize! :show, @arm
      @lesson = @arm.bit_core_tools.find_by_type("Tools::Learn")
    end

    # GET /think_feel_do_dashboard/arms/1/edit
    def edit
      @arm = Arm.find(params[:id])
      authorize! :edit, @arm
    end

    # PATCH/PUT /think_feel_do_dashboard/arms/1
    def update
      @arm = Arm.find(params[:id])
      authorize! :update, @arm
      if @arm.update(arm_params)
        redirect_to arm_path(@arm),
                    notice: "Arm was successfully updated.",
                    only: true
      else
        render :edit
      end
    end

    # DELETE /think_feel_do_dashboard/arms/1
    def destroy
      @arm = Arm.find(params[:id])
      authorize! :destroy, @arm
      redirect_to arm_path(@arm),
                  notice: "You do not have privileges to delete an arm. "\
                  "Please contact the site administrator to remove this arm."
    end

    private

    def arm_params
      params
        .require(:arm)
        .permit(
          :title, :is_social, :has_woz, :can_message_after_membership_complete
        )
    end

    def arm_not_found
      redirect_to arms_path,
                  alert: "The arm you were looking for no longer exists."
    end
  end
end

app/controllers/think_feel_do_dashboard/coach_assignments_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Used to associated coaches with participants
  class CoachAssignmentsController < ApplicationController
    before_action :set_participant
    before_action :set_coaches
    before_action :set_coach_assignment,
                  only: [:new, :show, :edit, :update, :destroy]

    # GET /think_feel_do_dashboard/participants/1/coaches/new
    def new
      authorize! :new, CoachAssignment
    end

    # POST /think_feel_do_dashboard/participants/1/coaches
    def create
      authorize! :create, CoachAssignment
      @coach_assignment = @participant.build_coach_assignment(
        coach_assignment_params
      )

      if @coach_assignment.save
        redirect_to participant_path(@participant),
                    notice: "Coach/Moderator was successfully assigned."
      else
        render :new
      end
    end

    # GET /think_feel_do_dashboard/participants/1/coaches/1
    def show
      authorize! :read, @coach_assignment
    end

    # GET /think_feel_do_dashboard/participants/1/coaches/1/edit
    def edit
      authorize! :edit, @coach_assignment
    end

    # PATCH/PUT /think_feel_do_dashboard/participants/1/coaches/1
    def update
      authorize! :update, @coach_assignment
      if @coach_assignment.update(coach_assignment_params)
        redirect_to participant_path(
          @participant
        ),
                    notice: "Coach/Moderator was successfully assigned."
      else
        render :edit
      end
    end

    # DELETE /think_feel_do_dashboard/participants/1/coaches/1
    def destroy
      authorize! :destroy, @coach_assignment
      if @coach_assignment.destroy
        redirect_to participant_path(@participant),
                    notice: "Coach/Moderator was successfully removed."
      else
        redirect_to participant_path(@participant),
                    alert: "There were errors."
      end
    end

    # GET /think_feel_do_dashboard/participants/1/coaches/woz
    def woz
      if @participant.coach
        set_coach_assignment
        authorize! :edit, @coach_assignment

        update_woz_coach
      else
        authorize! :new, CoachAssignment
        set_new_woz_coach
      end
    end

    private

    def set_new_woz_coach
      @coach_assignment = CoachAssignment.new(
        participant: @participant,
        coach_id: @participant.active_group.moderator_id
      )
      if @coach_assignment.save
        notification = "Coach/Moderator was successfully assigned"
      else
        notification = "An error occurred in the update of the "\
                              "participant's coach to the WOZ moderator."
      end
      redirect_to participant_path(@participant), notice: notification
    end

    def update_woz_coach
      @coach_assignment.update(coach_id: @participant.active_group.moderator_id)
      if @coach_assignment.save
        notification = "Coach/Moderator was successfully assigned "
      else
        notification = "An error occurred in the update of the "\
                              "participant's coach to the moderator."
      end
      redirect_to participant_path(@participant), notice: notification
    end

    def set_coaches
      @coaches = User.all.map { |user| [user.email, user.id] }
    end

    def set_participant
      @participant = Participant.find(params[:participant_id])
    end

    def set_coach_assignment
      @coach_assignment = @participant.coach_assignment ||
                          @participant.build_coach_assignment
    end

    def coach_assignment_params
      params
        .require(:coach_assignment)
        .permit(:coach_id)
    end
  end
end

app/controllers/think_feel_do_dashboard/concerns/browser_detective.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # Methods for browser type detection.
    module BrowserDetective
      extend ActiveSupport::Concern

      private

      # See http://richonrails.com/articles/action-pack-variants-in-rails-4-1
      def detect_browser
        request.variant = case request.user_agent
                          when /iPad/i
                            :tablet
                          when /iPhone|Windows Phone/i
                            :phone
                          when /Android/i && /mobile/i
                            :phone
                          when /Android/i
                            :tablet
                          else
                            :desktop
                          end
      end
    end
  end
end

app/controllers/think_feel_do_dashboard/concerns/invalid_auth_token.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # Rescues exception when authenticity token has expired
    module InvalidAuthToken
      extend ActiveSupport::Concern

      included do
        rescue_from ActionController::InvalidAuthenticityToken,
                    with: :invalid_auth_token_redirect
      end

      private

      def invalid_auth_token_redirect
        redirect_to root_path,
                    alert: "Your authenticity token expired. Please try again."
      end
    end
  end
end

app/controllers/think_feel_do_dashboard/groups_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Allows for the creation, updating, and deletion of groups
  class GroupsController < ApplicationController
    before_action :set_arms, :set_users
    before_action :set_group, :set_arm,
                  only: [:show, :edit, :update, :destroy]
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    # GET /think_feel_do_dashboard/groups
    def index
      authorize! :index, Group
      @groups = Group.all
    end

    # POST /think_feel_do_dashboard/groups
    def create
      @group = Group.new(group_params.except(:user_id))
      authorize! :create, @group

      if @group.save
        redirect_to @group,
                    notice: "Group was successfully created."
      else
        render :new
      end
    end

    # GET /think_feel_do_dashboard/groups/new
    def new
      authorize! :new, Group
      @group = Group.new
    end

    # GET /think_feel_do_dashboard/groups/1
    def show
      authorize! :show, @group
    end

    # GET /think_feel_do_dashboard/groups/1/edit
    def edit
      authorize! :edit, @group
    end

    # PATCH/PUT /think_feel_do_dashboard/groups/1
    def update
      authorize! :update, @group
      if @group.update(group_params.except(:user_id))
        redirect_to group_path(@group),
                    notice: "Group was successfully updated.",
                    only: true
      else
        render :edit
      end
    end

    # DELETE /think_feel_do_dashboard/groups/1
    def destroy
      authorize! :destroy, @group
      @group.destroy
      response_status = { notice: "Group was successfully destroyed." }
    rescue ActiveRecord::DeleteRestrictionError => e
      response_status = { alert: e.message }
    ensure
      redirect_to groups_url, response_status
    end

    private

    def set_group
      @group = Group.find(params[:id])
    end

    def set_arm
      @arm = @group.arm
    end

    def set_arms
      @arms = Arm.all
    end

    def set_users
      @users = User.all
    end

    def group_params
      params.require(:group).permit(
        :arm_id, :title, :moderator_id
      )
    end

    def record_not_found
      redirect_to main_app.root_path,
                  alert: "The group you are looking for no longer exists."
    end
  end
end

app/views/think_feel_do_dashboard/participants/_form.html.erb
<%= form_for(@participant, html: { role: :form }) do |f| %>
  <% if @participant.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <strong><%= pluralize(@participant.errors.count, "error") %> prohibited this participant from being saved:</strong>
      <ul>
      <% @participant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :study_id, "Study Id" %>
    <%= f.text_field :study_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone_number, "Phone Number" %>
    <%= f.text_field :phone_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :contact_preference, "Contact Preference" %>
    <%= f.select :contact_preference, options_for_select(@contact_preferences, @participant.contact_preference), { prompt: "Select how to be notified" }, class: "form-control" %>
  </div>

  <% unless @participant.new_record? %>
    <div class="form-group" id="password-form-group">
      <button id="password-generator" class="btn btn-warn">Generate password</button>
    </div>
  <% end %>

  <%= f.submit button_text, class: "btn btn-primary" %>
  <%= link_to "Cancel", cancel_path, class: "btn btn-default" %>
<% end %>

app/views/think_feel_do_dashboard/participants/edit.html.erb
<h1>Editing Participant</h1>

<%= render 'form', button_text: "Update", cancel_path: participant_path(@participant) %>

app/views/think_feel_do_dashboard/participants/index.html.erb
<h1>Participants</h1>

<div class="btn-toolbar" role="toolbar">
  <% if can? :new, Participant %>
    <%= link_to "New", new_participant_path, class: "btn btn-primary" %>
  <% end %>
</div>

<div class="list-group">
  <% @participants.each do |participant| %>
    <% if can? :show, participant %>
      <%= link_to membership_status(participant, participant.active_membership) + participant.study_id, participant, class: "list-group-item" %>
    <% end %>
  <% end %>
</div>

app/views/think_feel_do_dashboard/participants/new.html.erb
<h1>New Participant</h1>

<%= render 'form', button_text: "Create", cancel_path: participants_path %>

app/views/think_feel_do_dashboard/participants/show.html.erb
<h1>Participant</h1>

<div class="btn-toolbar" role="toolbar">
  <% if @participant.active_group && (can? :show, @participant.active_group) %>
    <%= link_to "Group", group_path(@participant.active_group), class: "btn btn-default" %>
  <% end %>
  <% if can? :edit, @participant %>
    <%= link_to "Edit", edit_participant_path(@participant), class: "btn btn-default" %>
  <% end %>
  <% if can? :destroy, @participant %>
    <%= link_to "Destroy", participant_path(@participant), method: :delete, data: { confirm: "Are you sure you want to delete this participant? All participant data will be deleted along with other participant data associated with this data. This action cannot be undone." }, class: "btn btn-danger" %>
  <% end %>
</div>

<p>
  <strong>Study Id:</strong>
  <%= @participant.study_id %>
</p>

<p>
  <strong>Email:</strong>
  <%= @participant.email %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= number_to_phone(@participant.phone_number, area_code: true) %>
</p>

<p>
  <strong>Contact Preference:</strong>
  <%= @participant.contact_preference.titleize %>
</p>

<% if social_features? %>
  <p>
    <strong>Display Name:</strong>
    <%= @participant.display_name.blank? ? "N/A" : @participant.display_name %>
  </p>
<% end %>

<p>
  <strong>Membership Status:</strong>
  <%= membership_status @participant, @participant.active_membership %>
</p>

<p>
  <strong>Current Group:</strong>
  <% if @participant.active_membership && @participant.active_membership.group %>
    <%= link_to @participant.active_group.title, group_path(@participant.active_group) %>
  <% else %>
    None
  <% end %>
</p>

<% if can? :update, @participant %>
  <p>
    <%= link_to "Assign New Group", new_participant_group_path(@participant), class: "btn btn-default" %>
  </p>
<% end %>

<p>
  <strong>Current Coach/Moderator:</strong>
  <% if @participant.coach %>
    <%= link_to @participant.coach.email, participant_coach_path(@participant, @participant.coach) %>
  <% else %>
    None
  <% end %>
</p>

<% if can? :update, @participant %>
  <p>
    <% if @participant.active_group_is_social? %>
      <%= link_to "Assign Coach/Moderator", woz_participant_coach_path(participant_id: @participant.id), class: "btn btn-default" %>
    <% elsif @participant.coach %>
      <%= link_to_if(@participant.memberships.any?, "Assign Coach/Moderator", edit_participant_coach_path(@participant, @participant.coach), class: "btn btn-default") %>
      <span class="help-block"><%= @participant.memberships.any? ? "" : "* Please assign Group first" %></span>
    <% else %>
      <%= link_to_if(@participant.memberships.any?, "Assign Coach/Moderator", new_participant_coach_path(@participant), class: "btn btn-default") %>
      <span class="help-block"><%= @participant.memberships.any? ? "" : "* Please assign Group first" %></span>
    <% end %>
  </p>
<% end %>

<% if can? :index, Membership %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Memberships</h3>
    </div>
    <div class="panel-body">
      Below lists the all groups this participant has been a member of and whether they are currently active or inactive.
    </div>
    <ul class="list-group">
      <% @participant.memberships.each do |membership| %>
        <%= link_to membership_status(@participant, membership) + membership.group.title, participant_group_path(@participant, membership.group), class: "list-group-item" %>
      <% end %>
    </ul>
  </div>
<% end %>