config/routes.rb
ThinkFeelDoDashboard::Engine.routes.draw do
  root to: "admin#index"
  resources :arms
  resources :groups do
    namespace :social_networking do
      resources :profile_questions
    end
    resource :moderators, only: :create
  end
  resources :participants do
    resources :coaches, controller: :coach_assignments, except: [:index] do
      get 'woz', on: :member
    end
    resources :groups, controller: :memberships, except: [:index]
  end
  resources :reports
  resources :users
end

app/models/group.rb
# A group is a collection of participants
# in the parent application, a group has a creator
class Group < ActiveRecord::Base
  belongs_to :arm
  has_many :memberships, dependent: :destroy
  has_many :participants, through: :memberships

  validates :arm, presence: true
  validates :title, presence: true, length: { maximum: 50 }

  def name
    title
  end
end

app/models/think_feel_do_dashboard/coach_assignment.rb
module ThinkFeelDoDashboard
  class CoachAssignment < ActiveRecord::Base
    belongs_to :coach, class_name: "User"
    belongs_to :participant

    validates :coach, :participant, presence: true

    delegate :name, to: :coach, prefix: true
    delegate :name, to: :participant, prefix: true
  end
end

app/models/think_feel_do_dashboard/concerns/group.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # Creates moderator and adds validations
    # and associations to group
    module Group
      extend ActiveSupport::Concern

      included do
        has_many :profile_questions,
                 class_name: "SocialNetworking::ProfileQuestion"
        belongs_to :moderator,
                   class_name: "User",
                   foreign_key: :moderator_id

        before_validation :create_moderator,
                          if: proc { |g| g.arm && g.arm.social? }

        validates :moderator_id,
                  presence: true,
                  if: proc { |g| g.arm && g.arm.social? }
      end

      def moderating_participant
        return if active_memberships.empty?
        active_participants.find_by_is_admin(true)
      end

      private

      def create_moderator
        unless moderating_participant
          begin
            create_moderating_participant
          rescue ActiveRecord::RecordInvalid => e
            errors.add(:base, "There were errors: #{e}")
          end
        end
      end

      def create_moderating_participant
        days = ENV["MODERATOR_LIFESPAN"] || 365

        ActiveRecord::Base.transaction do
          participant = create_participant(SecureRandom.hex(8))
          create_profile(participant.id)
          memberships.build(
            participant_id: participant.id,
            start_date: Time.zone.today,
            end_date: Time.zone.today.advance(days: days)
          )
        end
      end

      def create_participant(study_id)
        password = "1Aa" + SecureRandom.base64.gsub(/(.{1})/, '\1 ')

        ::Participant.create!(
          contact_preference: "email",
          display_name: Rails.application
                             .config
                             .moderating_participant_display_name,
          email: "#{study_id}@example.com",
          is_admin: true,
          password: password,
          password_confirmation: password,
          study_id: study_id
        )
      end

      def create_profile(participant_id)
        ::SocialNetworking::Profile.create!(
          participant_id: participant_id,
          icon_name: "admin",
          active: true
        )
      end
    end
  end
end

app/models/think_feel_do_dashboard/concerns/membership.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # addes necessary membership
    # associations and validations
    module Membership
      extend ActiveSupport::Concern

      # This is perfect for including functionality
      # provided by 3rd party gems, etc.
      included do
        attr_accessor :display_name

        before_validation :ensure_display_name_for_social_arms
        before_validation :only_one_active_group, on: :create

        validate :excludes_moderators
      end

      # methods added to Class itself...
      module ClassMethods
      end

      def active?
        (start_date.nil? || start_date <= Time.zone.today) &&
          (end_date.nil? || end_date >= Time.zone.today)
      end

      private

      def ensure_display_name_for_social_arms
        if invalid_display_name?
          errors.add(:display_name,
                     "is required because the arm of this intervention " \
                     "utilizes social features.")
        else
          name = display_name || participant.display_name
          participant.update_attributes(display_name: name)
        end
      end

      def excludes_moderators
        if active_group.try(:arm) &&
           !active_group.arm.social? &&
           participant.is_admin
          errors.add(:base, "moderators can't be part of this group.")
        end
      end

      def only_one_active_group
        if participant.active_membership && active?
          errors.add(:participant,
                     "can't be assigned to this group because they are " \
                     "already active.")
        end
      end

      def invalid_display_name?
        participant.active_membership &&
          active_group.try(:arm).try(:social?) &&
          participant.display_name.blank?
      end
    end
  end
end

app/models/think_feel_do_dashboard/concerns/participant_validations.rb
# validates phone numbers against Google api
require "phonelib"

module ThinkFeelDoDashboard
  module Concerns
    # is included in the Participant model and
    # checks whether a display_name needs to be set
    # if an arm is socila
    module ParticipantValidations
      extend ActiveSupport::Concern

      # This is perfect for including functionality
      # provided by 3rd party gems, etc.
      included do
        before_validation :ensure_phone_number, unless: "phone_number.blank?"
        before_validation :ensure_contact_preference
        before_validation :ensure_display_name
      end

      # methods added to Class itself...
      module ClassMethods
      end

      private

      def ensure_contact_preference
        if contact_preference == "phone" && phone_number.blank?
          errors.add(
            :phone_number,
            "can't be blank if your contact preference is phone."
          )
        end
      end

      def ensure_phone_number
        sanitized_num = Phonelib
                          .parse(phone_number)
                          .sanitized
        if Phonelib.valid?(sanitized_num)
          self.phone_number = sanitized_num
        else
          errors.add(:phone_number, "is not valid")
        end
      end

      def ensure_display_name
        active_membership.valid? if active_membership
      end
    end
  end
end

app/controllers/think_feel_do_dashboard/admin_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Allows the admin to navigate from page to page
  class AdminController < ApplicationController
    # GET /think_feel_do_dashboard
    def index
      authorize! :index, Arm
    end
  end
end

app/controllers/think_feel_do_dashboard/application_controller.rb
# frozen_string_literal: true
require "cancancan"

module ThinkFeelDoDashboard
  # Top level engine controller
  # inherits from host application's ApplicationController.
  class ApplicationController < ::ApplicationController
    include Concerns::BrowserDetective
    include Concerns::InvalidAuthToken

    before_action :authenticate_user!, :detect_browser
    check_authorization

    layout "application"

    rescue_from CanCan::AccessDenied do |exception|
      redirect_to root_url, alert: exception.message
    end
  end
end

app/controllers/think_feel_do_dashboard/arms_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Allows for the creation, updating, and deletion of arms
  class ArmsController < ApplicationController
    rescue_from ActiveRecord::RecordNotFound, with: :arm_not_found

    # GET /think_feel_do_dashboard/arms
    def index
      authorize! :index, Arm
      @arms = Arm.includes(:groups)
    end

    # POST /think_feel_do_dashboard/arms
    def create
      authorize! :create, Arm
      @arm = Arm.new(arm_params)
      if @arm.save
        redirect_to @arm,
                    notice: "Arm was successfully created."
      else
        render :new
      end
    end

    # GET /think_feel_do_dashboard/arms/new
    def new
      authorize! :new, Arm
      @arm = Arm.new
    end

    # GET /think_feel_do_dashboard/arms/1
    def show
      @arm = Arm.find(params[:id])
      authorize! :show, @arm
      @lesson = @arm.bit_core_tools.find_by_type("Tools::Learn")
    end

    # GET /think_feel_do_dashboard/arms/1/edit
    def edit
      @arm = Arm.find(params[:id])
      authorize! :edit, @arm
    end

    # PATCH/PUT /think_feel_do_dashboard/arms/1
    def update
      @arm = Arm.find(params[:id])
      authorize! :update, @arm
      if @arm.update(arm_params)
        redirect_to arm_path(@arm),
                    notice: "Arm was successfully updated.",
                    only: true
      else
        render :edit
      end
    end

    # DELETE /think_feel_do_dashboard/arms/1
    def destroy
      @arm = Arm.find(params[:id])
      authorize! :destroy, @arm
      redirect_to arm_path(@arm),
                  notice: "You do not have privileges to delete an arm. "\
                  "Please contact the site administrator to remove this arm."
    end

    private

    def arm_params
      params
        .require(:arm)
        .permit(
          :title, :is_social, :has_woz, :can_message_after_membership_complete
        )
    end

    def arm_not_found
      redirect_to arms_path,
                  alert: "The arm you were looking for no longer exists."
    end
  end
end

app/controllers/think_feel_do_dashboard/coach_assignments_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Used to associated coaches with participants
  class CoachAssignmentsController < ApplicationController
    before_action :set_participant
    before_action :set_coaches
    before_action :set_coach_assignment,
                  only: [:new, :show, :edit, :update, :destroy]

    # GET /think_feel_do_dashboard/participants/1/coaches/new
    def new
      authorize! :new, CoachAssignment
    end

    # POST /think_feel_do_dashboard/participants/1/coaches
    def create
      authorize! :create, CoachAssignment
      @coach_assignment = @participant.build_coach_assignment(
        coach_assignment_params
      )

      if @coach_assignment.save
        redirect_to participant_path(@participant),
                    notice: "Coach/Moderator was successfully assigned."
      else
        render :new
      end
    end

    # GET /think_feel_do_dashboard/participants/1/coaches/1
    def show
      authorize! :read, @coach_assignment
    end

    # GET /think_feel_do_dashboard/participants/1/coaches/1/edit
    def edit
      authorize! :edit, @coach_assignment
    end

    # PATCH/PUT /think_feel_do_dashboard/participants/1/coaches/1
    def update
      authorize! :update, @coach_assignment
      if @coach_assignment.update(coach_assignment_params)
        redirect_to participant_path(
          @participant
        ),
                    notice: "Coach/Moderator was successfully assigned."
      else
        render :edit
      end
    end

    # DELETE /think_feel_do_dashboard/participants/1/coaches/1
    def destroy
      authorize! :destroy, @coach_assignment
      if @coach_assignment.destroy
        redirect_to participant_path(@participant),
                    notice: "Coach/Moderator was successfully removed."
      else
        redirect_to participant_path(@participant),
                    alert: "There were errors."
      end
    end

    # GET /think_feel_do_dashboard/participants/1/coaches/woz
    def woz
      if @participant.coach
        set_coach_assignment
        authorize! :edit, @coach_assignment

        update_woz_coach
      else
        authorize! :new, CoachAssignment
        set_new_woz_coach
      end
    end

    private

    def set_new_woz_coach
      @coach_assignment = CoachAssignment.new(
        participant: @participant,
        coach_id: @participant.active_group.moderator_id
      )
      if @coach_assignment.save
        notification = "Coach/Moderator was successfully assigned"
      else
        notification = "An error occurred in the update of the "\
                              "participant's coach to the WOZ moderator."
      end
      redirect_to participant_path(@participant), notice: notification
    end

    def update_woz_coach
      @coach_assignment.update(coach_id: @participant.active_group.moderator_id)
      if @coach_assignment.save
        notification = "Coach/Moderator was successfully assigned "
      else
        notification = "An error occurred in the update of the "\
                              "participant's coach to the moderator."
      end
      redirect_to participant_path(@participant), notice: notification
    end

    def set_coaches
      @coaches = User.all.map { |user| [user.email, user.id] }
    end

    def set_participant
      @participant = Participant.find(params[:participant_id])
    end

    def set_coach_assignment
      @coach_assignment = @participant.coach_assignment ||
                          @participant.build_coach_assignment
    end

    def coach_assignment_params
      params
        .require(:coach_assignment)
        .permit(:coach_id)
    end
  end
end

app/controllers/think_feel_do_dashboard/concerns/browser_detective.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # Methods for browser type detection.
    module BrowserDetective
      extend ActiveSupport::Concern

      private

      # See http://richonrails.com/articles/action-pack-variants-in-rails-4-1
      def detect_browser
        request.variant = case request.user_agent
                          when /iPad/i
                            :tablet
                          when /iPhone|Windows Phone/i
                            :phone
                          when /Android/i && /mobile/i
                            :phone
                          when /Android/i
                            :tablet
                          else
                            :desktop
                          end
      end
    end
  end
end

app/controllers/think_feel_do_dashboard/concerns/invalid_auth_token.rb
# frozen_string_literal: true
module ThinkFeelDoDashboard
  module Concerns
    # Rescues exception when authenticity token has expired
    module InvalidAuthToken
      extend ActiveSupport::Concern

      included do
        rescue_from ActionController::InvalidAuthenticityToken,
                    with: :invalid_auth_token_redirect
      end

      private

      def invalid_auth_token_redirect
        redirect_to root_path,
                    alert: "Your authenticity token expired. Please try again."
      end
    end
  end
end

app/controllers/think_feel_do_dashboard/groups_controller.rb
# frozen_string_literal: true
require_dependency "think_feel_do_dashboard/application_controller"

module ThinkFeelDoDashboard
  # Allows for the creation, updating, and deletion of groups
  class GroupsController < ApplicationController
    before_action :set_arms, :set_users
    before_action :set_group, :set_arm,
                  only: [:show, :edit, :update, :destroy]
    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    # GET /think_feel_do_dashboard/groups
    def index
      authorize! :index, Group
      @groups = Group.all
    end

    # POST /think_feel_do_dashboard/groups
    def create
      @group = Group.new(group_params.except(:user_id))
      authorize! :create, @group

      if @group.save
        redirect_to @group,
                    notice: "Group was successfully created."
      else
        render :new
      end
    end

    # GET /think_feel_do_dashboard/groups/new
    def new
      authorize! :new, Group
      @group = Group.new
    end

    # GET /think_feel_do_dashboard/groups/1
    def show
      authorize! :show, @group
    end

    # GET /think_feel_do_dashboard/groups/1/edit
    def edit
      authorize! :edit, @group
    end

    # PATCH/PUT /think_feel_do_dashboard/groups/1
    def update
      authorize! :update, @group
      if @group.update(group_params.except(:user_id))
        redirect_to group_path(@group),
                    notice: "Group was successfully updated.",
                    only: true
      else
        render :edit
      end
    end

    # DELETE /think_feel_do_dashboard/groups/1
    def destroy
      authorize! :destroy, @group
      @group.destroy
      response_status = { notice: "Group was successfully destroyed." }
    rescue ActiveRecord::DeleteRestrictionError => e
      response_status = { alert: e.message }
    ensure
      redirect_to groups_url, response_status
    end

    private

    def set_group
      @group = Group.find(params[:id])
    end

    def set_arm
      @arm = @group.arm
    end

    def set_arms
      @arms = Arm.all
    end

    def set_users
      @users = User.all
    end

    def group_params
      params.require(:group).permit(
        :arm_id, :title, :moderator_id
      )
    end

    def record_not_found
      redirect_to main_app.root_path,
                  alert: "The group you are looking for no longer exists."
    end
  end
end

app/views/think_feel_do_dashboard/groups/_form.html.erb
<%= form_for(@group, html: { role: :form }) do |f| %>
  <% if @group.errors.any? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <strong><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</strong>
      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= label_tag "group[arm_id]", "Arm" %>
    <%= select_tag "group[arm_id]", options_from_collection_for_select(@arms, :id, :title, @arm.try(:id)), prompt: "Select Arm", class: "form-control" %>
  </div>
  <% if social_features? %>
    <div class="form-group">
      <%= f.label :moderator_id, "Coach/Moderator" %>
      <%= f.collection_select(:moderator_id, @users, :id, :email, { prompt: "Select Coach/Moderator" }, { class: "form-control" }) %>
      <p class="help-block">All notifications are emailed to this user's email</p>
    </div>
  <% end %>
  <%= f.submit button_text, class: "btn btn-primary" %>
  <%= link_to "Cancel", cancel_path, class: "btn btn-default" %>
<% end %>

app/views/think_feel_do_dashboard/groups/_group_item_link.html.erb
<% if can? :show, group %>
  <%= link_to group.title, group_path(group), class: "list-group-item" %>
<% end %>

app/views/think_feel_do_dashboard/groups/_groups.html.erb
<div class="list-group">
  <% groups.each do |group| %>
    <%= render "think_feel_do_dashboard/groups/group_item_link", group: group %>
  <% end %>
</div>

app/views/think_feel_do_dashboard/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', button_text: "Update", cancel_path: group_path(@group) %>

app/views/think_feel_do_dashboard/groups/index.html.erb
<h1>Groups</h1>

<div class="btn-toolbar" role="toolbar">
  <% if can? :new, Group %>
    <%= link_to "New", new_group_path, class: "btn btn-primary" %>
  <% end %>
</div>

<%= render "groups", groups: @groups %>

app/views/think_feel_do_dashboard/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', button_text: "Create", cancel_path: groups_path %>

app/views/think_feel_do_dashboard/groups/show.html.erb
<h1>Group</h1>

<div class="btn-toolbar" role="toolbar">
  <div class="btn-group">
    <%= link_to "Arm", arm_path(@group.arm), class: "btn btn-default" %>
  </div>

  <% if can? :index, PhqAssessment %>
    <div class="btn-group">
      <%= link_to "Patient Dashboard", (defined?(think_feel_do_engine) ? think_feel_do_engine.coach_group_patient_dashboards_path(@group) : root_path), class: "btn btn-default" %>
      <% if @group.arm.is_social %>
        <%= link_to "Group Dashboard", (defined?(think_feel_do_engine) ? think_feel_do_engine.coach_group_group_dashboard_index_path(@group) : root_path), class: "btn btn-default" %>
      <% end %>
    </div>
  <% end %>

  <% if can?(:index, Message) || can?(:index, SiteMessage) %>
    <div class="btn-group">
      <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
        Messaging <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu">
        <li>
          <% if can? :index, Message %>
            <%= link_to "Messages", (defined?(think_feel_do_engine) ? think_feel_do_engine.coach_group_messages_path(@group) : root_path) %>
          <% end %>
        </li>
        <li>
          <% if can? :index, SiteMessage %>
            <%= link_to "Site Messaging", (defined?(think_feel_do_engine) ? think_feel_do_engine.coach_group_site_messages_path(@group) : root_path) %>
          <% end %>
        </li>
      </ul>
    </div>
  <% end %>

  <% if can?(:moderate, @group) && @group.arm.social? %>
    <%= link_to "Moderate", group_moderators_path(@group), method: :post, class: "btn btn-default", target: "_blank" if social_features? %>
    <%= link_to "Manage Profile Questions", group_social_networking_profile_questions_path(@group), class: "btn btn-default" %>
  <% end %>
  <% if can? :update, @group %>
    <%= link_to "Manage Tasks", (defined?(think_feel_do_engine) ? think_feel_do_engine.arm_manage_tasks_group_path(@group.arm, @group) : root_path), class: "btn btn-default" %>
  <% end %>

  <% if can? :edit, @group %>
    <%= link_to "Edit", edit_group_path(@group), class: "btn btn-default" %>
  <% end %>
  <% if can? :destroy, @group %>
    <%= link_to "Destroy", group_path(@group), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  <% end %>
</div>

<p>
  <strong>Title:</strong>
  <%= @group.title %>
</p>

<p>
  <strong>Arm:</strong>
  <%= link_to(@group.arm.title, arm_path(@group.arm)) %>
</p>

<% if @group.respond_to?(:moderator) %>
  <p>
    <strong>Coach/Moderator:</strong>
    <%= @group.moderator ? link_to_if((can? :read, @group.moderator), @group.moderator.email, user_path(@group.moderator)) : "None" %>
  </p>
<% end %>

<% if can? :index, Participant %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Participant Info</h3>
    </div>
    <div class="list-group">
      <% Membership.where(group_id: @group.id).each do |membership| %>
        <% if can? :show, membership.participant %>
          <%= link_to membership.participant.study_id, participant_path(membership.participant), class: "list-group-item clearfix" %>
          <% end %>
      <% end %>
    </div>
  </div>
<% end %>